package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/Nativu5/qweather-cli/internal/catalog"
	"github.com/Nativu5/qweather-cli/internal/output"
)

const generatedHeader = "<!-- Code generated by `go run ./tools/skill generate`; DO NOT EDIT. -->\n"

type generatedReference struct {
	path string
	data []byte
}

func buildGeneratedReferences(root string) ([]generatedReference, error) {
	version, err := readVersion(root)
	if err != nil {
		return nil, err
	}
	registry, err := catalog.Default()
	if err != nil {
		return nil, fmt.Errorf("load capability registry: %w", err)
	}
	resultSchema, err := buildResultSchemaReference(version)
	if err != nil {
		return nil, err
	}
	return []generatedReference{
		{path: filepath.Join(root, defaultSkillPath, "references", "command-reference.md"), data: buildCommandReference(version, registry)},
		{path: filepath.Join(root, defaultSkillPath, "references", "result-schema.md"), data: resultSchema},
	}, nil
}

func writeGeneratedReferences(root string) error {
	references, err := buildGeneratedReferences(root)
	if err != nil {
		return err
	}
	for _, reference := range references {
		if err := writeFileAtomically(reference.path, reference.data, 0o644); err != nil {
			return err
		}
	}
	return syncSkillInstallVersion(root)
}

func syncSkillInstallVersion(root string) error {
	version, err := readVersion(root)
	if err != nil {
		return err
	}
	path := filepath.Join(root, defaultSkillPath, "SKILL.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read Skill instructions: %w", err)
	}
	pattern := regexp.MustCompile(`npm install --global qweather-cli@[^\x60\s]+`)
	matches := pattern.FindAllIndex(data, -1)
	if len(matches) != 1 {
		return fmt.Errorf("SKILL.md must contain exactly one fixed-version npm install command; found %d", len(matches))
	}
	want := []byte("npm install --global qweather-cli@" + version)
	updated := pattern.ReplaceAll(data, want)
	if bytes.Equal(updated, data) {
		return nil
	}
	return writeFileAtomically(path, updated, 0o644)
}

func checkGeneratedReferences(root string) error {
	references, err := buildGeneratedReferences(root)
	if err != nil {
		return err
	}
	for _, reference := range references {
		actual, err := os.ReadFile(reference.path)
		if err != nil {
			return fmt.Errorf("read generated reference %s: %w", reference.path, err)
		}
		if !bytes.Equal(actual, reference.data) {
			return fmt.Errorf("generated reference %s is stale; run `make skill-generate`", reference.path)
		}
	}
	return nil
}

func checkVersionSync(root string) error {
	version, err := readVersion(root)
	if err != nil {
		return err
	}
	packageBytes, err := os.ReadFile(filepath.Join(root, "packages", "npm", "package.json"))
	if err != nil {
		return fmt.Errorf("read npm package metadata: %w", err)
	}
	var packageMetadata struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(packageBytes, &packageMetadata); err != nil {
		return fmt.Errorf("decode npm package metadata: %w", err)
	}
	if packageMetadata.Version != version {
		return fmt.Errorf("npm version %s does not match VERSION %s", packageMetadata.Version, version)
	}
	skillBytes, err := os.ReadFile(filepath.Join(root, defaultSkillPath, "SKILL.md"))
	if err != nil {
		return fmt.Errorf("read Skill instructions: %w", err)
	}
	want := "npm install --global qweather-cli@" + version
	if count := bytes.Count(skillBytes, []byte(want)); count != 1 {
		return fmt.Errorf("SKILL.md must contain exactly one fixed-version install command %q; found %d", want, count)
	}
	installPattern := regexp.MustCompile(`npm install --global qweather-cli@[^\x60\s]+`)
	for _, command := range installPattern.FindAllString(string(skillBytes), -1) {
		if command != want {
			return fmt.Errorf("Skill install version drift: found %q, want %q", command, want)
		}
	}
	return nil
}

func readVersion(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "VERSION"))
	if err != nil {
		return "", fmt.Errorf("read VERSION: %w", err)
	}
	version := strings.TrimSpace(string(data))
	if !regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$`).MatchString(version) {
		return "", fmt.Errorf("VERSION %q is not stable SemVer", version)
	}
	return version, nil
}

func buildCommandReference(version string, registry *catalog.Registry) []byte {
	var output bytes.Buffer
	output.WriteString(generatedHeader)
	output.WriteString("\n# QWeather command reference\n\n")
	fmt.Fprintf(&output, "Version: `%s`\n\nSource: compiled Go Capability registry.\n\n", version)
	output.WriteString("Use only Current Capabilities below. Provider paths and authentication are implementation details owned by the binary.\n\n")
	output.WriteString("## Common execution flags\n\n")
	output.WriteString("`--config <path>`, `--profile <name>`, `--timeout <duration>`, `--output text|json|body`, `--refresh`, `--no-cache`, and `--debug` apply according to the CLI contract. Successful query data goes to stdout; diagnostics and failures go to stderr.\n\n")
	current := registry.Current()
	fmt.Fprintf(&output, "## Current Capabilities (%d)\n\n", len(current))
	for _, capability := range current {
		fmt.Fprintf(&output, "### `qweather %s`\n\n", capability.CommandPath)
		fmt.Fprintf(&output, "- Capability: `%s`\n", capability.ID)
		fmt.Fprintf(&output, "- Purpose: %s\n", capability.Summary)
		fmt.Fprintf(&output, "- Target: `%s`\n", capability.Target)
		fmt.Fprintf(&output, "- Billing group: `%s`\n", capability.BillingGroup)
		fmt.Fprintf(&output, "- Product Gate: `%s`\n", capability.ProductGate)
		fmt.Fprintf(&output, "- Cache: `%s`", capability.Cache.Mode)
		if capability.Cache.TTL > 0 {
			fmt.Fprintf(&output, ", TTL `%s`", capability.Cache.TTL)
		}
		if capability.Cache.InactiveTTL > 0 {
			fmt.Fprintf(&output, ", inactive TTL `%s`", capability.Cache.InactiveTTL)
		}
		fmt.Fprintf(&output, ", boundary `%s`\n", capability.Cache.Boundary)
		fmt.Fprintf(&output, "- Response family: `%s`\n", capability.Upstream.ResponseFamily)
		fmt.Fprintf(&output, "- Official documentation: <%s>\n", capability.DocsURL)
		if len(capability.Flags) == 0 {
			output.WriteString("- Capability flags: none\n\n")
			continue
		}
		output.WriteString("\n| Flag | Required | Type | Constraints/default | Meaning |\n")
		output.WriteString("| --- | --- | --- | --- | --- |\n")
		for _, flag := range capability.Flags {
			fmt.Fprintf(&output, "| `--%s` | %s | `%s` | %s | %s |\n", flag.Name, yesNo(flag.Required), flag.Kind, flagConstraints(flag), escapeTable(flag.Usage))
		}
		output.WriteByte('\n')
	}
	tombstones := registry.Deprecated()
	fmt.Fprintf(&output, "## Tombstones (%d)\n\n", len(tombstones))
	output.WriteString("Tombstones are lookup-only lifecycle records. They have no executable command and cannot be enabled by a flag.\n\n")
	output.WriteString("| Capability | Summary | Replacement | Documentation |\n")
	output.WriteString("| --- | --- | --- | --- |\n")
	for _, capability := range tombstones {
		replacement := "none documented"
		if capability.Replacement != "" {
			replacement = "`" + capability.Replacement + "`"
		}
		fmt.Fprintf(&output, "| `%s` | %s | %s | <%s> |\n", capability.ID, escapeTable(capability.Summary), replacement, capability.DocsURL)
	}
	return output.Bytes()
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func flagConstraints(flag catalog.Flag) string {
	values := make([]string, 0)
	if len(flag.Enum) > 0 {
		values = append(values, "one of `"+strings.Join(flag.Enum, "`, `")+"`")
	}
	if len(flag.IntEnum) > 0 {
		numbers := make([]string, len(flag.IntEnum))
		for index, value := range flag.IntEnum {
			numbers[index] = strconv.Itoa(value)
		}
		values = append(values, "one of `"+strings.Join(numbers, "`, `")+"`")
	}
	if flag.Min != nil || flag.Max != nil {
		minimum, maximum := "unbounded", "unbounded"
		if flag.Min != nil {
			minimum = strconv.FormatFloat(*flag.Min, 'f', -1, 64)
		}
		if flag.Max != nil {
			maximum = strconv.FormatFloat(*flag.Max, 'f', -1, 64)
		}
		values = append(values, "range `"+minimum+".."+maximum+"`")
	}
	if flag.Default != "" {
		values = append(values, "default `"+flag.Default+"`")
	}
	if len(values) == 0 {
		return "—"
	}
	return strings.Join(values, "; ")
}

func escapeTable(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}

type schemaField struct {
	path        string
	typeName    string
	required    bool
	description string
}

func buildResultSchemaReference(version string) ([]byte, error) {
	var rendered bytes.Buffer
	rendered.WriteString(generatedHeader)
	rendered.WriteString("\n# Machine result and problem reference\n\n")
	fmt.Fprintf(&rendered, "Version: `%s`\n\nSources: Go output types, schema constants, and stable problem-code catalog.\n\n", version)
	rendered.WriteString("Select `--output json` when exact field paths or JSON value types matter. JSON is compact; pipe it to `jq` for formatting.\n\n")
	if err := writeSchemaTable(&rendered, "Machine Result", output.ResultSchema, reflect.TypeFor[output.Result](), resultDescriptions()); err != nil {
		return nil, err
	}
	if err := writeSchemaTable(&rendered, "Machine Problem", output.ProblemSchema, reflect.TypeFor[output.Problem](), problemDescriptions()); err != nil {
		return nil, err
	}
	definitions := output.ProblemDefinitions()
	fmt.Fprintf(&rendered, "## Stable problem codes (%d)\n\n", len(definitions))
	rendered.WriteString("Branch on `code`; use the exit status only as a coarse shell category. `retryable` in an emitted problem is authoritative for that occurrence.\n\n")
	rendered.WriteString("| Code | Exit | Normally retryable | Meaning |\n")
	rendered.WriteString("| --- | ---: | --- | --- |\n")
	for _, definition := range definitions {
		fmt.Fprintf(&rendered, "| `%s` | `%d` | %s | %s |\n", definition.Code, definition.ExitCode, yesNo(definition.Retryable), definition.Meaning)
	}
	rendered.WriteString("\n## Provider Body mode\n\n")
	rendered.WriteString("`--output body` is valid only for a successful provider query. It writes the byte-exact successful Provider Body with no added newline. Failures remain QWeather-owned Text Problems on stderr and never expose provider error bodies.\n")
	return rendered.Bytes(), nil
}

func writeSchemaTable(buffer *bytes.Buffer, title, schema string, root reflect.Type, descriptions map[string]string) error {
	fields, err := collectSchemaFields(root, "", true, descriptions)
	if err != nil {
		return fmt.Errorf("build %s field reference: %w", title, err)
	}
	fmt.Fprintf(buffer, "## %s: `%s`\n\n", title, schema)
	buffer.WriteString("| Field | JSON type | Presence | Meaning |\n")
	buffer.WriteString("| --- | --- | --- | --- |\n")
	for _, field := range fields {
		fmt.Fprintf(buffer, "| `%s` | `%s` | %s | %s |\n", field.path, field.typeName, map[bool]string{true: "required", false: "optional"}[field.required], field.description)
	}
	buffer.WriteByte('\n')
	return nil
}

func collectSchemaFields(root reflect.Type, prefix string, parentRequired bool, descriptions map[string]string) ([]schemaField, error) {
	fields := make([]schemaField, 0)
	for index := 0; index < root.NumField(); index++ {
		field := root.Field(index)
		tag := field.Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}
		parts := strings.Split(tag, ",")
		name := parts[0]
		path := name
		if prefix != "" {
			path = prefix + "." + name
		}
		optional := len(parts) > 1 && slicesContains(parts[1:], "omitempty")
		typeName, nested := schemaType(field.Type)
		description, ok := descriptions[path]
		if !ok {
			return nil, fmt.Errorf("missing generated schema description for %s", path)
		}
		fields = append(fields, schemaField{path: path, typeName: typeName, required: parentRequired && !optional, description: description})
		if nested != nil {
			nestedFields, err := collectSchemaFields(nested, path, parentRequired && !optional, descriptions)
			if err != nil {
				return nil, err
			}
			fields = append(fields, nestedFields...)
		}
	}
	return fields, nil
}

func schemaType(value reflect.Type) (string, reflect.Type) {
	if value == reflect.TypeFor[json.RawMessage]() {
		return "object", nil
	}
	if value.Kind() == reflect.Pointer {
		value = value.Elem()
	}
	switch value.Kind() {
	case reflect.Struct:
		return "object", value
	case reflect.String:
		return "string", nil
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "integer", nil
	case reflect.Slice:
		if value.Elem().Kind() == reflect.String {
			return "array<string>", nil
		}
		return "array<any>", nil
	case reflect.Interface:
		return "any", nil
	default:
		return value.String(), nil
	}
}

func slicesContains(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

func resultDescriptions() map[string]string {
	return map[string]string{
		"schema": "Always `qweather.result/v1`.", "outcome": "`ok` or valid `no_data`.", "capability": "Stable Capability ID.",
		"resolvedPlace": "Invocation-scoped Resolved Place; omitted when no resolution occurred.", "resolvedPlace.id": "QWeather Location ID.",
		"resolvedPlace.name": "Provider place name.", "resolvedPlace.adm1": "First-level administrative area.", "resolvedPlace.adm2": "Second-level administrative area.",
		"resolvedPlace.country": "Provider country or region.", "resolvedPlace.lat": "Provider latitude string.", "resolvedPlace.lon": "Provider longitude string.",
		"resolvedPlace.tz": "Provider time-zone identifier.", "operations": "Logical Capability IDs used for this result.", "policy": "Applied project policy.",
		"policy.billingGroup": "`basic`, `marine`, or `solar`.", "cache": "Cache outcome for the data operation.", "cache.status": "`hit`, `miss`, `disabled`, or another documented cache state.",
		"cache.storedAt": "RFC3339 storage time when applicable.", "cache.expiresAt": "RFC3339 hard expiration when applicable.", "cache.ageSeconds": "Whole-second cached age when applicable.",
		"cache.upstreamRequested": "Whether the data operation reached QWeather.", "upstream": "Provider response metadata.", "upstream.httpStatus": "HTTP status for the provider result.",
		"upstream.responseFamily": "`code-refer-v1`, `metadata-v1`, or `console-v1`.", "attribution": "Convenient complete Attribution view; provider fields remain in data.",
		"data": "Complete decoded provider JSON object, including unknown fields.",
	}
}

func problemDescriptions() map[string]string {
	return map[string]string{
		"schema": "Always `qweather.problem/v1`.", "code": "Stable symbolic decision code.", "message": "Safe human-readable summary.",
		"capability": "Capability ID when failure occurred after selection.", "retryable": "Whether this occurrence may be deliberately retried.",
		"details": "Complete safe structured details; shape depends on code.",
	}
}

func writeFileAtomically(path string, data []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".qweather-skill-*")
	if err != nil {
		return fmt.Errorf("create temporary file for %s: %w", path, err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return fmt.Errorf("set mode for %s: %w", path, err)
	}
	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return fmt.Errorf("write temporary file for %s: %w", path, err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close temporary file for %s: %w", path, err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace %s: %w", path, err)
	}
	return nil
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
